sudo: false
language: node_js
services:
  - mongodb
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "iojs"

script:
  - sleep 15 # sleep to wait for mongodb
  - cd test && npm install && npm test
