language: node_js
services:
  - mongodb
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs"

before_script:
  - sleep 15
  - cd test && npm install && npm test
